
dist: bionic
script:
  - sudo ./travis-build.sh

branches:
  only:
    - master
    - development

deploy:
  - provider: script
    script: wget -qO - https://raw.githubusercontent.com/Nitrux/nitrux-repository-util/master/upload-pkgs | sh -s *.deb
    skip_cleanup: true

notifications:
  email: false
  